[package]
name = "ai-meme-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.0"
reqwest = { version = "0.12.22", features = ["json", "blocking"] }
tokio = { version = "1.46.1", features = ["full"] }