[package]
name = "ai-meme-generator"
version = "0.2.0"
edition = "2024"
description = "Simple text renderer using image templates."

[dependencies]
image = "0.25.6"
imageproc = "0.25.0"
ab_glyph = "0.2"